Add shift filters to csp decorators
columnflow/columnflow pull request #255
Opened 2023-07-03 09:01 UTC by riga

Our CSP (calibrator, selector, producer) decorators already have flags like `data_only` or `mc_only` which control whether the underlying task array function should be applied in case they are evaluated in a dataset that is not data or mc.

Along the same lines, this PR adds additional flags to make a similar decision based on the currently processes shift. It is possible to set

- `nominal_only`, to skip the CSP in case a systematic variation is processed, or
- `shifts_only`, for a more fine-grained control of the shifts that should actually be not skipped.

The implementation is identical through the three decorators.

2023-07-05 12:05 UTC, dsavoiu requested changes
This looks good overall. I only have a comment and a suggestion below (only added for the `Calibrator` class, but they are of course valid also for `Producer` and `Selector`).

2023-07-06 08:12 UTC, riga commented on columnflow/calibration/__init__.py
> +            if mc_only or data_only or nominal_only:
I added this to all CSPs :+1:

2023-07-06 08:13 UTC, riga commented on columnflow/calibration/__init__.py
>              if mc_only and data_only:
Yep :+1: Added.

2023-07-06 09:27 UTC, riga commented
Ready to re-review or merge from my side :)

2023-07-06 12:33 UTC, dsavoiu approved these changes
Thanks for the changes! Good to merge from my side.

2023-07-06 13:01 UTC, merged