Change SelectionResult structure, add bool checks.
columnflow/columnflow pull request #340
Opened 2023-10-30 17:33 UTC by riga

This PR slightly restructures the contents of the `SelectionResult` and adds a couple sanity checks as documented in #336 and #337.

Changes to `SelectionResult`:

- The main event mask used to be stored under `result.main.event`. This is now simply `result.main`.
- Other top-level fields (besides objects and steps) were also stored under `result.main.*` before but are now moved to `result.*` as well.

Added checks:

- When converting to arrays via the `to_ak()` method, there is now a check in place that verifies that event masks are booleans. We strictly require that to preserve the order of events across columns written in different places throughout columnflow.
- Inside `SelectEvents` an error is raised now in case the `selector_inst` return a `SelectionResult` that has no event mask set. This is not entirely necessary per se, but we have some producers and other helpers that access the event mask, and it is cleaner to force the mask being there (which it is anyway in 99% of the cases), instead of having to do conditional checks in N places.

Fixes #336 and #337.

2023-10-30 17:34 UTC, riga commented
Also adding @mafrahm , @JulesVandenbroeck and @gsaha009 here since this might require a change on their end.

2023-11-01 10:10 UTC, pkausw requested changes
Nice PR, thanks @riga! Just some minor changes and clarifications :+1:

2023-11-01 10:20 UTC, riga commented on columnflow/selection/__init__.py
> +        if self.event is not None and getattr(ak.type(self.event).content, "primitive", None) != "bool":
Yup, the "primitive" attribute is a actually a string, so the comparison here should be independent of the underlying type.

2023-11-01 10:23 UTC, riga commented on columnflow/selection/__init__.py
> +        :raises ValueError: If the main events mask contains a type other than bool.
Added

2023-11-01 10:31 UTC, riga commented on columnflow/selection/__init__.py
>                  "Muon": {
I rephrased the comments slightly to be in line with the comments above that block.

2023-11-01 10:35 UTC, pkausw approved these changes
LGTM :+1:

2023-11-01 11:31 UTC, merged

2023-11-07 09:32 UTC, JulesVandenbroeck commented
Hi, I tried to adapt the code after pulling from master. However afterwards It seems I can no longer update SelectionResult objects (aka: _results += lepton_results_) due to the error message "*** TypeError: cannot pickle 'dict_keys' object". As I am new to columnflow I am mainly following the example of the hh2bbww analysis (which has not yet pushed this change). In case the answer is not obvious, I linked the [gitlab of my project](https://gitlab.cern.ch/juvanden/ttz) (selection is under ttz/selection/default.py")