Feature/get events from categories
columnflow/columnflow pull request #365
Opened 2023-11-27 11:42 UTC by mafrahm

Closes #352

2023-11-27 12:22 UTC, pkausw requested changes
Nice PR @mafrahm ! I think it would be nice to further test things that are not supposed to work, both to make sure that unexpected behaviors are less probable and also for more clarity of how this module is supposed to work

2023-11-27 12:22 UTC, pkausw commented on columnflow/config_util.py
> +    into one the leafs of one of the *categories*.
```suggestion
    into one of the leafs of one of the *categories*.
```

2023-11-27 12:22 UTC, pkausw commented on tests/test_config_util.py
> +    def test_get_events_from_categories(self):
You could probably split this test into each of the different blocks (i.e. smaller unit tests), but this is optional imho

2023-11-27 12:22 UTC, pkausw commented on tests/test_config_util.py
> +
The new helper also `raises` an Exception at some point, would also be good to test this explicitely

2023-12-08 13:49 UTC, riga approved these changes
LGTM!

2023-12-08 13:54 UTC, merged