add plot_profile function
columnflow/columnflow pull request #407
Opened 2024-03-14 14:03 UTC by mafrahm

This task adds the possibilty to create profile plots

```
        law run cf.PlotVariables1D --version prod1 --processes st_tchannel_t \
            --variables jet1_pt-jet2_pt \
            --plot-function columnflow.plotting.plot_functions_1d.plot_profile
```
(tested with hh2bbww analysis)
![plot__proc_st_tchannel_t__cat_incl__var_jet1_pt-jet2_pt](https://github.com/columnflow/columnflow/assets/49306645/9017dede-f4a4-4125-b380-4890b22182d2)

I also fixed a minor inconsistency with plot colors when no color was set for a process

2024-03-15 09:16 UTC, mafrahm commented
I also added the possibility to add the base distribution of the profiled variable. Here is another exemplary plot

![profile1](https://github.com/columnflow/columnflow/assets/49306645/cafc8f7c-a6f6-4aa6-98ce-91d3b7031535)

2024-05-31 13:03 UTC, riga requested changes
Looks good!
Just 3 minor things inline.

2024-05-31 13:03 UTC, riga commented on columnflow/plotting/plot_functions_1d.py
> +    .. code-block:: bash
`code-block` needs to be followed by an empty line for sphinx to render this properly.

2024-05-31 13:03 UTC, riga commented on columnflow/plotting/plot_util.py
> +def get_profile_variations(h_in: hist.Hist, axis: int = 1) -> dict(str, hist.Hist):
The return type looks fishy. I guess `dict[str, hist.Hist]`?

2024-05-31 13:03 UTC, riga commented on columnflow/plotting/plot_util.py
> +def get_profile_width(h_in: hist.Hist, axis: int = 1) -> (np.array, np.array):
Return type should be `tuple[np.array, np.array]`.

2024-05-31 16:27 UTC, riga approved these changes

2024-05-31 16:42 UTC, merged