BUG: `tenacity` version 8.4.0 doesn't work
columnflow/columnflow pull request #475
Opened 2024-06-17 12:02 UTC by haddadanas

`tenacity` current version 8.4.0 doesn't work with `columnflow` (or rather the current `luigi` version). Rerunning the github linting actions will directly lead to the error.
This PR set tenacity to the previous release until Spotify fixes the problem (Issue for Spotify is created [luigi#3292](https://github.com/spotify/luigi/issues/3292))

The Error
```
 columnflow/__init__.py:11: in <module>
    import law
modules/law/law/__init__.py:35: in <module>
    import luigi
data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/luigi/__init__.py:34: in <module>
    from luigi import rpc
data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/luigi/rpc.py:33: in <module>
    from tenacity import Retrying, wait_fixed, stop_after_attempt
data/software/venvs/venv_columnar_dev_3cbb5aff/lib/python3.9/site-packages/tenacity/__init__.py:653: in <module>
    from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
E   ModuleNotFoundError: No module named 'tenacity.asyncio'
```

2024-06-18 11:30 UTC, haddadanas commented
The bug has been fixed from `tenacity` side (with version 8.4.1). But maybe it would make sense to fix the version. Else this PR can be closed :smile:

2024-06-21 07:57 UTC, riga requested changes
Good catch! I made an inline suggestion though to exclude the failing version.

2024-06-21 07:57 UTC, riga commented on sandboxes/cf.txt
> +tenacity==8.3.0
Instead of pinning a specific version, I would just exclude the version that is known to fail.

```suggestion
tenacity!=8.4.0
```

2024-06-22 09:13 UTC, riga approved these changes
:+1:

2024-06-22 09:13 UTC, merged