Feature: Added the possibility to blind data points
columnflow/columnflow pull request #515
Opened 2024-07-22 15:52 UTC by haddadanas

if the sensitivity (S/sqrt(S + B) of MC processes) is above a threshold in a bin, the data point are set to 0.

The threshold can be given in the CLI or alternatively can be set to a default in the config via: `self.config_inst.x.default_blinding_threshold`

Also needed is to define the signal processes in the config via:
a dict entry called signals in the `cfg.x.process_groups`

2024-07-22 16:27 UTC, riga requested changes
Nice! Just a couple inline comments.

2024-07-22 16:27 UTC, riga commented on columnflow/tasks/framework/plotting.py
> +        default=-1.0,
`law.NO_FLOAT` :)

2024-07-22 16:27 UTC, riga commented on columnflow/tasks/framework/plotting.py
> +        "via a dictionary in the `default_blinding_threshold` auxiliary in the config; "
Can be removed.

2024-07-22 16:27 UTC, riga commented on columnflow/plotting/plot_util.py
> +def blind_sensitivity(hists: OrderedDict, config_inst: od.Config, threshold: float | None) -> hist.Hist:
- `hists: dict[od.Process, hist.Hist]`
- `threshold: float`
- `-> dict[od.Process, hist.Hist]`

2024-07-22 16:27 UTC, riga commented on columnflow/plotting/plot_util.py
> +    that is called "signals" to know, where the signal processes are defined (regex allowed).
Add comment about returned copies.

2024-07-22 16:27 UTC, riga commented on columnflow/plotting/plot_util.py
> +        return hists
Can be dropped.

2024-07-22 16:27 UTC, riga commented on columnflow/plotting/plot_util.py
> +    )
Include subprocesses.

2024-07-22 16:27 UTC, riga commented on columnflow/plotting/plot_util.py
> +    backgrounds = {proc: hist for proc, hist in hists.items() if proc not in signals and proc.is_mc}
Return hists unchanged in case any of the three dicts is empty.

2024-07-22 21:00 UTC, haddadanas commented
Feedback is implemented however naf is currently down, so I couldn't test it :eyes: 
Will do this tomorrow in the morning

2024-07-23 07:37 UTC, riga requested changes
Some last comments before we can merge :)

2024-07-23 07:37 UTC, riga commented on analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py
> +    "signals": [],  # list of signal parent processes e.g. tt, hh etc. (required for some tasks)
```suggestion
    "signals": [],  # list of signal parent processes e.g. h, hh etc. (needed for some features)
```

2024-07-23 07:37 UTC, riga commented on columnflow/plotting/plot_functions_1d.py
> +    blind_sensitivity,
Could you rename the function to `blind_sensitive_bins`?

2024-07-23 07:37 UTC, riga commented on columnflow/plotting/plot_util.py
> +    The histograms are not changed inplace, but The function return a copy of the modified histograms.
```suggestion
    The histograms are not changed inplace, but copies of the modified histograms are returned.
```

2024-07-23 07:37 UTC, riga commented on columnflow/tasks/framework/plotting.py
> +        "defaults to the `default_blinding_threshold` aux field if not given via CLI",
```suggestion
        description="parameter to blind datapoints in the region where the sensitivity s/sqrt(s+b) "
        "exceeds a certain threshold; defaults to the `default_blinding_threshold` aux field of "
        "the config",
```

2024-07-23 13:32 UTC, riga approved these changes

2024-07-23 13:32 UTC, merged