Include hist hook for datacards
columnflow/columnflow pull request #539
Opened 2024-08-22 14:10 UTC by pkausw

In the current version, the `cf.CreateDatacards` task cannot use hist hooks. This PR implements this feature. The histograms are first loaded in the same format as in the plotting routines for consistency. Moreover, process objects can now indicate that they should be dereived dynamically with a new property called `is_dynamic`. The datasets attached to dynamic processes are not considered when resolving the task requirements, which should reduce unnecessary overhead.

Additionally, this PR also updates the doc strings of the `InferenceModel` class. No new information was added, but now the parameters should be parsed properly.

This PR needs to be tested a little more, but should be mergable soon.

2024-10-17 07:27 UTC, mafrahm commented
Hi @pkausw, I just thought about the usecase of rebinning for hist hooks in datacards. We typically use the same observable/variable in multiple categories, but we would like to perform the rebinning for each category separately. Would that be possible with your PR?

2024-10-17 09:02 UTC, pkausw commented
> Hi @pkausw, I just thought about the usecase of rebinning for hist hooks in datacards. We typically use the same observable/variable in multiple categories, but we would like to perform the rebinning for each category separately. Would that be possible with your PR?

In principle it would be possible since you can create new histograms from scratch. Not sure if this nice and easy to understand, but I guess that is up to the analyzers :+1:

2025-02-04 13:19 UTC, mafrahm approved these changes

2025-02-04 13:19 UTC, mafrahm commented on columnflow/tasks/cms/inference.py
> +                        # ],
```suggestion
```

2025-02-05 13:09 UTC, pkausw commented
After talking to @riga, I adopted the docs part of this PR such that the `automodule` command for sphinx also works with empty `__all__` lists. This PR should now be ready for merging

2025-02-05 14:01 UTC, riga requested changes
Thanks!

I just had two minor comments for which I provided code suggestions, looks good otherwise.

2025-02-06 08:34 UTC, pkausw commented
Thanks for the review @riga, I implemented your suggestions :+1:

2025-02-06 11:19 UTC, riga approved these changes
LGTM!

2025-02-06 11:19 UTC, merged