Update muon and electron SF producers (backward compatible)
columnflow/columnflow pull request #556
Opened 2024-10-24 14:31 UTC by nprouvost

create ElectronSFConfig and MuonSFConfig objects and update producer accordingly

TODO: decide if Trigger SF Producer should be implemented with the ID/ISO producers or by updating functions during Producer initialisation

2024-11-14 17:16 UTC, mafrahm commented
Regarding your TODO, I don't think that we need any code changes to cover the trigger SFs. You can simply derive new producers to produce different sets of correction weights. I am already doing that in my analysis:

https://github.com/uhh-cms/hh2bbww/blob/master/hbw/production/weights.py#L117-L128

2024-11-15 12:09 UTC, nprouvost commented
> Regarding your TODO, I don't think that we need any code changes to cover the trigger SFs. You can simply derive new producers to produce different sets of correction weights. I am already doing that in my analysis:
> 
> https://github.com/uhh-cms/hh2bbww/blob/master/hbw/production/weights.py#L117-L128

After discussion with marcel we decided to add it, since it is something every cms analysis should have (if they plan to use muon triggers) and it shows an example on how to do it if different derives are needed. (Actually, is it in the documentation at all at the moment? I can't remember) So it is in fact not a TODO anymore but part of the PR

2024-12-06 11:38 UTC, nprouvost commented on columnflow/production/cms/electron.py
> +        return obj if isinstance(obj, cls) else cls(*obj)
done, does this fit your needs?

2024-12-13 10:30 UTC, riga requested changes
Looks very good, thanks @nprouvost .

I made some inline coding suggestions and added them, nothing to complain about the overall logic and backwards compatibility :+1:

2024-12-13 10:30 UTC, riga commented on columnflow/production/cms/muon.py
> +            raise ValueError(f"cannot convert {obj} to MuonSFConfig")
De-nesting. Also, unordered sets are not supported.

```suggestion
        if isinstance(obj, cls):
            return obj
        if isinstance(obj, str):
            return cls(obj)
        if isinstance(obj, (list, tuple)):
            return cls(*obj)
        if isinstance(obj, dict):
            return cls(**obj)
        raise ValueError(f"cannot convert {obj} to MuonSFConfig")
```

2024-12-13 10:30 UTC, riga commented on columnflow/production/cms/muon.py
> +    campaign: str
Optional.

```suggestion
    campaign: str = ""
```

2024-12-13 10:33 UTC, riga requested changes

2024-12-13 10:33 UTC, riga commented on columnflow/production/cms/electron.py
>      produces={"electron_weight{,_up,_down}"},
```suggestion
    produces in the init
```

2024-12-13 10:35 UTC, riga requested changes

2024-12-13 10:35 UTC, riga commented on columnflow/production/cms/electron.py
> +    produces in the init
```suggestion
    # produces in the init
```

2024-12-13 10:38 UTC, riga approved these changes

2024-12-13 10:38 UTC, merged